// =============================================================================
// Dữ liệu đối chiếu Trạch Nhật — CHÉP TỪ licham365.vn, KHÔNG sinh từ code của
// chính dự án này.
//
// Cách thu thập: tải trang `https://licham365.vn/lich-am-ngay-{D}-thang-{M}-nam-{Y}`
// của từng ngày rồi bóc các trường hiển thị. Vì vậy đây là đối chiếu với **nguồn
// ngoài**, đúng yêu cầu "không tự sinh reference từ chính mình" — khác với
// `bat_tu_ref_data.rs` (giai đoạn 4) vốn tự sinh từ prototype Python nội bộ.
//
// 52 ngày = 24 ngày rải đều 1995–2030 (nhiều tháng, nhiều mùa, gồm cả đầu và
// cuối tháng Âm lịch) + 28 ngày chọn có chủ đích quanh các ca khó:
//   * 6 ngày "trùng Trực" (Trực lặp lại tại mốc giao tiết khí);
//   * 6 ngày tháng Âm lịch KHÁC tháng tiết khí — đây là các ca phân biệt được
//     quy tắc Trực đúng (tháng tiết khí) với quy tắc sai (tháng Âm lịch);
//   * 10 ngày dính Tam Nương / Nguyệt Kỵ / Sát Chủ, gồm cả ngày dính 2 mục;
//   * 6 ngày lệch đã biết, giữ lại để LECH_DA_BIET không mục ruỗng.
//
// Quy ước index: Can Giáp=0..Quý=9; Chi Tý=0..Hợi=11;
// Trực Kiến=0, Trừ=1, Mãn=2, Bình=3, Định=4, Chấp=5, Phá=6, Nguy=7, Thành=8,
// Thu=9, Khai=10, Bế=11.
// =============================================================================

#[allow(dead_code)]
pub struct RefDay {
    /// Ngày Dương lịch "YYYY-MM-DD".
    pub date: &'static str,
    /// Ngày Âm lịch licham365 hiển thị.
    pub lunar_day: u8,
    /// Tháng Âm lịch licham365 hiển thị.
    pub lunar_month: u8,
    /// Can của ngày (0..9).
    pub day_can: u8,
    /// Chi của ngày (0..11).
    pub day_chi: u8,
    /// Tên tiết khí licham365 hiển thị.
    pub tiet: &'static str,
    /// Trực (0..11).
    pub truc: u8,
    /// Kết luận ngày: `1` = Hoàng đạo, `0` = Hắc đạo, `2` = licham365 ghi
    /// "Bình thường" (site chỉ liệt kê 8/12 vị Thần nên 4 vị còn lại thành
    /// "bình thường" — với các ngày này ta KHÔNG ràng buộc kết luận tốt/xấu).
    pub hoang_dao: u8,
    /// Chi của các khung giờ Hoàng Đạo (đã sắp tăng dần).
    pub gio_hoang_dao: &'static [u8],
    /// Các điều kiêng kỵ licham365 gắn cho ngày này.
    pub kieng_ky: &'static [&'static str],
}


pub const REF_DAYS: &[RefDay] = &[
    RefDay {
        date: "1995-07-04",
        lunar_day: 7, lunar_month: 6,
        day_can: 2, day_chi: 8,
        tiet: "Hạ Chí",
        truc: 2,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &["TamNuong"],
    },
    RefDay {
        date: "2000-02-29",
        lunar_day: 25, lunar_month: 1,
        day_can: 3, day_chi: 5,
        tiet: "Vũ Thủy",
        truc: 3,
        hoang_dao: 1,
        gio_hoang_dao: &[1, 4, 6, 7, 10, 11],
        kieng_ky: &["SatChu"],
    },
    RefDay {
        date: "2005-10-17",
        lunar_day: 15, lunar_month: 9,
        day_can: 0, day_chi: 10,
        tiet: "Hàn Lộ",
        truc: 0,
        hoang_dao: 0,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2010-09-22",
        lunar_day: 15, lunar_month: 8,
        day_can: 1, day_chi: 11,
        tiet: "Bạch Lộ",
        truc: 2,
        hoang_dao: 0,
        gio_hoang_dao: &[1, 4, 6, 7, 10, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2013-04-30",
        lunar_day: 21, lunar_month: 3,
        day_can: 2, day_chi: 2,
        tiet: "Cốc Vũ",
        truc: 10,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &[],
    },
    RefDay {
        date: "2016-08-22",
        lunar_day: 20, lunar_month: 7,
        day_can: 2, day_chi: 0,
        tiet: "Lập Thu",
        truc: 4,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &[],
    },
    RefDay {
        date: "2018-04-16",
        lunar_day: 1, lunar_month: 3,
        day_can: 4, day_chi: 2,
        tiet: "Thanh Minh",
        truc: 10,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &[],
    },
    RefDay {
        date: "2019-02-05",
        lunar_day: 1, lunar_month: 1,
        day_can: 9, day_chi: 9,
        tiet: "Lập Xuân",
        truc: 7,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &[],
    },
    RefDay {
        date: "2020-01-25",
        lunar_day: 1, lunar_month: 1,
        day_can: 3, day_chi: 3,
        tiet: "Đại Hàn",
        truc: 2,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &[],
    },
    RefDay {
        date: "2021-06-10",
        lunar_day: 1, lunar_month: 5,
        day_can: 5, day_chi: 1,
        tiet: "Mang Chủng",
        truc: 7,
        hoang_dao: 1,
        gio_hoang_dao: &[2, 3, 5, 8, 10, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2022-11-03",
        lunar_day: 10, lunar_month: 10,
        day_can: 6, day_chi: 8,
        tiet: "Sương Giáng",
        truc: 10,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &[],
    },
    RefDay {
        date: "2023-05-18",
        lunar_day: 29, lunar_month: 3,
        day_can: 2, day_chi: 0,
        tiet: "Lập Hạ",
        truc: 7,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-01-03",
        lunar_day: 22, lunar_month: 11,
        day_can: 2, day_chi: 2,
        tiet: "Đông Chí",
        truc: 2,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &["SatChu", "TamNuong"],
    },
    RefDay {
        date: "2024-02-05",
        lunar_day: 26, lunar_month: 12,
        day_can: 5, day_chi: 11,
        tiet: "Lập Xuân",
        truc: 9,
        hoang_dao: 1,
        gio_hoang_dao: &[1, 4, 6, 7, 10, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-02-08",
        lunar_day: 29, lunar_month: 12,
        day_can: 8, day_chi: 2,
        tiet: "Lập Xuân",
        truc: 0,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-03-07",
        lunar_day: 27, lunar_month: 1,
        day_can: 6, day_chi: 6,
        tiet: "Kinh Trập",
        truc: 3,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &["TamNuong"],
    },
    RefDay {
        date: "2024-03-08",
        lunar_day: 28, lunar_month: 1,
        day_can: 7, day_chi: 7,
        tiet: "Kinh Trập",
        truc: 4,
        hoang_dao: 1,
        gio_hoang_dao: &[2, 3, 5, 8, 10, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-03-15",
        lunar_day: 6, lunar_month: 2,
        day_can: 4, day_chi: 2,
        tiet: "Kinh Trập",
        truc: 11,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-04-11",
        lunar_day: 3, lunar_month: 3,
        day_can: 1, day_chi: 5,
        tiet: "Thanh Minh",
        truc: 1,
        hoang_dao: 1,
        gio_hoang_dao: &[1, 4, 6, 7, 10, 11],
        kieng_ky: &["TamNuong"],
    },
    RefDay {
        date: "2024-06-13",
        lunar_day: 8, lunar_month: 5,
        day_can: 4, day_chi: 8,
        tiet: "Mang Chủng",
        truc: 2,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &["SatChu"],
    },
    RefDay {
        date: "2024-09-05",
        lunar_day: 3, lunar_month: 8,
        day_can: 8, day_chi: 8,
        tiet: "Xử Thử",
        truc: 0,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &["TamNuong"],
    },
    RefDay {
        date: "2025-12-31",
        lunar_day: 12, lunar_month: 11,
        day_can: 0, day_chi: 10,
        tiet: "Đông Chí",
        truc: 10,
        hoang_dao: 2,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2027-03-08",
        lunar_day: 1, lunar_month: 2,
        day_can: 2, day_chi: 10,
        tiet: "Kinh Trập",
        truc: 7,
        hoang_dao: 2,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2030-11-11",
        lunar_day: 16, lunar_month: 10,
        day_can: 6, day_chi: 10,
        tiet: "Lập Đông",
        truc: 11,
        hoang_dao: 2,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-11-05",
        lunar_day: 5, lunar_month: 10,
        day_can: 9, day_chi: 9,
        tiet: "Sương Giáng",
        truc: 11,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["NguyetKy", "SatChu"],
    },
    RefDay {
        date: "2024-11-06",
        lunar_day: 6, lunar_month: 10,
        day_can: 0, day_chi: 10,
        tiet: "Sương Giáng",
        truc: 11,
        hoang_dao: 2,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-12-05",
        lunar_day: 5, lunar_month: 11,
        day_can: 9, day_chi: 3,
        tiet: "Tiểu Tuyết",
        truc: 4,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["NguyetKy"],
    },
    RefDay {
        date: "2024-12-06",
        lunar_day: 6, lunar_month: 11,
        day_can: 0, day_chi: 4,
        tiet: "Đại Tuyết",
        truc: 4,
        hoang_dao: 2,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2025-01-04",
        lunar_day: 5, lunar_month: 12,
        day_can: 9, day_chi: 9,
        tiet: "Đông Chí",
        truc: 9,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["NguyetKy", "SatChu"],
    },
    RefDay {
        date: "2025-01-05",
        lunar_day: 6, lunar_month: 12,
        day_can: 0, day_chi: 10,
        tiet: "Tiểu Hàn",
        truc: 9,
        hoang_dao: 1,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &[],
    },
    RefDay {
        date: "2024-10-07",
        lunar_day: 5, lunar_month: 9,
        day_can: 0, day_chi: 4,
        tiet: "Thu Phân",
        truc: 6,
        hoang_dao: 1,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &["NguyetKy"],
    },
    RefDay {
        date: "2025-02-02",
        lunar_day: 5, lunar_month: 1,
        day_can: 8, day_chi: 2,
        tiet: "Đại Hàn",
        truc: 1,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &["NguyetKy"],
    },
    RefDay {
        date: "2025-04-02",
        lunar_day: 5, lunar_month: 3,
        day_can: 7, day_chi: 1,
        tiet: "Xuân Phân",
        truc: 10,
        hoang_dao: 0,
        gio_hoang_dao: &[2, 3, 5, 8, 10, 11],
        kieng_ky: &["NguyetKy", "SatChu"],
    },
    RefDay {
        date: "2025-04-03",
        lunar_day: 6, lunar_month: 3,
        day_can: 8, day_chi: 2,
        tiet: "Xuân Phân",
        truc: 11,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &[],
    },
    RefDay {
        date: "2025-06-04",
        lunar_day: 9, lunar_month: 5,
        day_can: 0, day_chi: 4,
        tiet: "Tiểu Mãn",
        truc: 11,
        hoang_dao: 2,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &["SatChu"],
    },
    RefDay {
        date: "2025-08-29",
        lunar_day: 7, lunar_month: 7,
        day_can: 6, day_chi: 6,
        tiet: "Xử Thử",
        truc: 10,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &["SatChu", "TamNuong"],
    },
    RefDay {
        date: "2024-02-16",
        lunar_day: 7, lunar_month: 1,
        day_can: 6, day_chi: 10,
        tiet: "Lập Xuân",
        truc: 8,
        hoang_dao: 2,
        gio_hoang_dao: &[2, 4, 5, 8, 9, 11],
        kieng_ky: &["TamNuong"],
    },
    RefDay {
        date: "2024-04-21",
        lunar_day: 13, lunar_month: 3,
        day_can: 1, day_chi: 3,
        tiet: "Cốc Vũ",
        truc: 11,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["TamNuong"],
    },
    RefDay {
        date: "2024-03-14",
        lunar_day: 5, lunar_month: 2,
        day_can: 3, day_chi: 1,
        tiet: "Kinh Trập",
        truc: 10,
        hoang_dao: 0,
        gio_hoang_dao: &[2, 3, 5, 8, 10, 11],
        kieng_ky: &["NguyetKy", "SatChu"],
    },
    RefDay {
        date: "2024-05-21",
        lunar_day: 14, lunar_month: 4,
        day_can: 1, day_chi: 9,
        tiet: "Tiểu Mãn",
        truc: 4,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["NguyetKy", "SatChu"],
    },
    RefDay {
        date: "2024-02-18",
        lunar_day: 9, lunar_month: 1,
        day_can: 8, day_chi: 0,
        tiet: "Lập Xuân",
        truc: 10,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &["SatChu"],
    },
    RefDay {
        date: "2024-06-17",
        lunar_day: 12, lunar_month: 5,
        day_can: 8, day_chi: 0,
        tiet: "Mang Chủng",
        truc: 6,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &["SatChu"],
    },
    RefDay {
        date: "2024-03-16",
        lunar_day: 7, lunar_month: 2,
        day_can: 5, day_chi: 3,
        tiet: "Kinh Trập",
        truc: 0,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["SatChu", "TamNuong"],
    },
    RefDay {
        date: "2024-10-15",
        lunar_day: 13, lunar_month: 9,
        day_can: 8, day_chi: 0,
        tiet: "Hàn Lộ",
        truc: 2,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &["SatChu", "TamNuong"],
    },
    RefDay {
        date: "2025-05-10",
        lunar_day: 13, lunar_month: 4,
        day_can: 5, day_chi: 3,
        tiet: "Lập Hạ",
        truc: 10,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["SatChu", "TamNuong"],
    },
    RefDay {
        date: "2025-06-08",
        lunar_day: 13, lunar_month: 5,
        day_can: 4, day_chi: 8,
        tiet: "Mang Chủng",
        truc: 2,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &["SatChu", "TamNuong"],
    },
    RefDay {
        date: "2026-08-19",
        lunar_day: 7, lunar_month: 7,
        day_can: 1, day_chi: 1,
        tiet: "Lập Thu",
        truc: 5,
        hoang_dao: 1,
        gio_hoang_dao: &[2, 3, 5, 8, 10, 11],
        kieng_ky: &["SatChu", "TamNuong"],
    },
    RefDay {
        date: "2025-02-03",
        lunar_day: 6, lunar_month: 1,
        day_can: 9, day_chi: 3,
        tiet: "Đại Hàn",
        truc: 1,
        hoang_dao: 0,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &[],
    },
    RefDay {
        date: "2025-03-05",
        lunar_day: 6, lunar_month: 2,
        day_can: 9, day_chi: 9,
        tiet: "Vũ Thủy",
        truc: 6,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &[],
    },
    RefDay {
        date: "2025-07-06",
        lunar_day: 12, lunar_month: 6,
        day_can: 2, day_chi: 0,
        tiet: "Hạ Chí",
        truc: 5,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 3, 6, 8, 9],
        kieng_ky: &[],
    },
    RefDay {
        date: "2026-02-03",
        lunar_day: 16, lunar_month: 12,
        day_can: 4, day_chi: 8,
        tiet: "Đại Hàn",
        truc: 6,
        hoang_dao: 2,
        gio_hoang_dao: &[0, 1, 4, 5, 7, 10],
        kieng_ky: &[],
    },
    RefDay {
        date: "2025-05-04",
        lunar_day: 7, lunar_month: 4,
        day_can: 9, day_chi: 9,
        tiet: "Cốc Vũ",
        truc: 5,
        hoang_dao: 1,
        gio_hoang_dao: &[0, 2, 3, 6, 7, 9],
        kieng_ky: &["SatChu", "TamNuong"],
    },
];
